INSERT INTO products (itemName, price, info, category) VALUES
('Aurora Citrus Sparkling Water',   2.99,   'A crisp sparkling water infused with radiant citrus essence, like drinking morning light.', 'Sparkling Water'),
('Midnight Berry Elixir Soda',      3.49,   'Deep berry soda with a dark fruit profile and a smooth, mysterious finish.', 'Soda'),
('Honeydew Cloud Milk Tea',         4.25,   'Light milk tea blended with honeydew for a soft, creamy sweetness.', 'Milk Tea'),
('Volcanic Mango Energy Drink',     3.99,   'Explosive tropical mango energy drink with a bold caffeine kick.', 'Energy Drink'),
('Iced Lavender Oat Latte',         5.50,   'Creamy oat milk latte infused with calming lavender and chilled perfection.', 'Latte'),
('Frozen Pineapple Breeze Juice',   3.75,   'Frozen pineapple juice that tastes like a tropical windstorm in a glass.', 'Juice'),
('Celestial Cola Classic',          2.49,   'A timeless cola with a cosmic twist of extra fizz and caramel depth.', 'Soda'),
('Dragonfruit Stardust Smoothie',   6.25,   'Thick dragonfruit smoothie sprinkled with a stardust-like berry blend.', 'Smoothie'),
('Spiced Chai Nebula Brew',         4.95,   'Warm chai infused with cosmic spices and a velvety finish.', 'Tea'),
('Matcha Moonbeam Latte',           5.75,   'Earthy matcha latte glowing with subtle sweetness and creamy milk.', 'Latte'),
('Cherry Blossom Fizz Soda',        3.25,   'Floral cherry blossom soda with a delicate, sparkling finish.', 'Soda'),
('Arctic Mint Cold Brew Coffee',    4.50,   'Extra chilled cold brew coffee with a sharp, refreshing mint edge.', 'Coffee'),
('Golden Turmeric Sunrise Shot',    2.99,   'A wellness shot of turmeric and citrus designed to brighten your day.', 'Wellness Shot'),
('Blackberry Twilight Refresher',   3.95,   'Refreshing blackberry drink with a dusk-like berry sweetness.', 'Refresher'),
('Cola Mirage Electrolyte Drink',   3.50,   'Hydrating coconut electrolyte drink with a smooth tropical illusion.', 'Electrolyte Drink'),
('Peach Comet Iced Tea',            3.30,   'Sweet peach iced tea that streaks across your palate like a comet.', 'Iced Tea'),
('Vanilla Drift Cream Soda',        3.10,   'Classic cream soda with drifting vanilla warmth and soft fizz.', 'Cream Soda'),
('Strawberry Nebula Smoothie',      6.75,   'Thick strawberry smoothie you can sip or spoon, packed with cosmic fruit energy.', 'Smoothie'),
('Lemon Zest Thunderade',           2.89,   'Electric lemonade with a sharp citrus bolt and refreshing punch.', 'Lemonade'),
('Caramel Cloud Macchiato Frappe',  5.95,   'Layered caramel frappe with cloud-like foam and rich espresso.', 'Frappe'),
('Blue Raspberry Hypernova Slush',  4.10,   'Frozen blue raspberry slush that explodes with intense fruity flavor.', 'Slush'),
('Hibiscus Drift Botanical Soda',   3.60,   'Floral hibiscus soda with botanical elegance and light carbonation.', 'Soda'),
('Espresso Orbit Shot',             2.50,   'A concentrated espresso shot with orbital-level intensity.', 'Coffee'),
('Watermelon Aurora Cooler',        3.85,   'Juicy watermelon cooler with aurora-like freshness and crisp finish.', 'Cooler'),
('Toasted Coconut Sky Latte',       5.40,   'Toasted coconut latte with a warm, airy sky-inspired flavor profile.', 'Latte');